version: '3.8'

services:
  # Microservicio de Despachos (Spring Boot)
  back-despachos:
    # En producción y CD, descarga la imagen directamente desde tu Docker Hub
    image: ${DOCKER_HUB_USER}/back-despachos:latest
    container_name: back-despachos-container
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - proyecto-network

  # Microservicio de Ventas (Spring Boot)
  back-ventas:
    image: ${DOCKER_HUB_USER}/back-ventas:latest
    container_name: back-ventas-container
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - proyecto-network

  # Frontend (React / Vite)
  front-despacho:
    image: ${DOCKER_HUB_USER}/front-despacho:latest
    container_name: front-despacho-container
    ports:
      - "80:80"
    depends_on:
      - back-despachos
      - back-ventas
    networks:
      - proyecto-network

networks:
  proyecto-network:
    driver: bridge