# Etapa 1: Compilación del proyecto con Maven
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Etapa 2: Entorno de ejecución ligero (CORREGIDO CON TEMURIN)
FROM eclipse-temurin:17-jre-slim
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]