# Etapa 1: Compilación del proyecto con Maven
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

# Copiar el archivo pom.xml del microservicio de ventas
COPY pom.xml .

# Copiar el código fuente
COPY src ./src

# Compilar y empaquetar el .jar sin ejecutar los tests
run mvn clean package -DskipTests

# Etapa 2: Entorno de ejecución ligero
FROM openjdk:17-jdk-slim
WORKDIR /app

# Copiar el .jar compilado en la etapa de build
COPY --from=build /app/target/*.jar app.jar

# Exponer el puerto de Spring Boot
EXPOSE 8080

# Comando para levantar la aplicación de ventas
ENTRYPOINT ["java", "-jar", "app.jar"]