# Etapa 1: Compilación del proyecto con Maven
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Etapa 2: Entorno de ejecución ligero
FROM amazoncorretto:17-alpine
WORKDIR /app

# Crear un usuario sin privilegios para no correr la app como Root
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]